### ISSUE TITLE
Support TTL clean up

### ISSUE THREAD

**Issue by m-spyratos** [socketio/socket.io-mongo-emitter#2]
The [MongoDB Adapter](https://socket.io/docs/v4/mongo-adapter) gives you the option to clean up the documents by [using a TTL index](https://socket.io/docs/v4/mongo-adapter/#usage-with-a-ttl-index):

```
await mongoCollection.createIndex(
  { createdAt: 1 },
  { expireAfterSeconds: 3600, background: true }
  );

io.adapter(createAdapter(mongoCollection, {
  addCreatedAtField: true
}));
```

This emitter though, does not add the `createdAt` value when calling `this.mongoCollection.insertOne`, so all documents inserted along with their packets stay in the collection.

**Comment by darrachequesne** [comment]
Thanks for the heads-up!

This was implemented in https://github.com/socketio/socket.io-mongo-emitter/commit/3b6d5a99fb5100e07dd45a103ab65d41eef91636, included in version [0.2.0](https://github.com/socketio/socket.io-mongo-emitter/releases/tag/0.2.0). Have a great day!
